In [1]:
import numpy as np

## DataTypes and Attributes

In [2]:
# NumPy's main datatype is ndarray 
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([
    [1,3,5.5],
    [4.5,7,8]
])
# 3-dimensional array, also referred to as a matrix
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])

In [5]:
a2

array([[1. , 3. , 5.5],
       [4.5, 7. , 8. ]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape

(3,)

In [8]:
a3.shape

(2, 3, 3)

In [9]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [10]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [11]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [12]:
a1

array([1, 2, 3])

In [13]:
a2

array([[1. , 3. , 5.5],
       [4.5, 7. , 8. ]])

In [14]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [15]:
# create a dataframe from numpy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  3.0  5.5
1  4.5  7.0  8.0

## 2. Create Numpy arrays

In [16]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [17]:
sample_array.dtype

dtype('int64')

In [18]:
ones = np.ones((2, 3))

In [19]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
ones.dtype

dtype('float64')

In [21]:
type(ones)

numpy.ndarray

In [22]:
zeros = np.zeros((2, 3))

In [23]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
range_array = np.arange(0, 10,2)

In [25]:
range_array

array([0, 2, 4, 6, 8])

In [26]:
random_array = np.random.randint(0,10,size=(3,5))
random_array

array([[5, 9, 6, 2, 7],
       [0, 0, 3, 0, 6],
       [4, 9, 8, 8, 1]])

In [27]:
random_array.size

15

In [28]:
random_array.shape

(3, 5)

In [29]:
random_array_2 = np.random.random(size=(5, 3))
random_array_2

array([[0.76993785, 0.41197676, 0.19640304],
       [0.00612584, 0.99079343, 0.33040136],
       [0.36689018, 0.109049  , 0.37619476],
       [0.24636461, 0.03628896, 0.90835907],
       [0.68370078, 0.20274632, 0.74939818]])

In [30]:
random_array_2.shape

(5, 3)

In [31]:
random_array_2.size

15

In [32]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.4270494 , 0.8915376 , 0.69744371],
       [0.52441422, 0.77215739, 0.89381159],
       [0.19673831, 0.86595141, 0.4601171 ],
       [0.17141633, 0.51204374, 0.75944154],
       [0.19122383, 0.2389463 , 0.75408368]])

In [33]:
#pseudo random arrays|
np.random.seed(seed=0)

random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [34]:
np.random.seed(7)
random_array_5 = np.random.random(size=((5, 3)))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [35]:
random_array_4.shape

(5, 3)

## 3. Viewing arrays and matrices

In [36]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
a1

array([1, 2, 3])

In [38]:
a2

array([[1. , 3. , 5.5],
       [4.5, 7. , 8. ]])

In [39]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [40]:
a1[0]

1

In [41]:
a2[0]

array([1. , 3. , 5.5])

In [42]:
a3.shape

(2, 3, 3)

In [43]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
a2

array([[1. , 3. , 5.5],
       [4.5, 7. , 8. ]])

In [45]:
a2[1]

array([4.5, 7. , 8. ])

In [46]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [47]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [48]:
a4 = np.random.randint(10, size=(2,3,4,5))

In [49]:
a4

array([[[[3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7],
         [3, 3, 8, 3, 0]],

        [[1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4],
         [3, 1, 3, 1, 3]],

        [[4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0],
         [9, 9, 3, 4, 5]]],


       [[[3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5],
         [7, 1, 5, 4, 4]],

        [[9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6],
         [9, 8, 6, 5, 9]],

        [[7, 5, 4, 9, 6],
         [8, 1, 5, 5, 8],
         [3, 7, 7, 9, 4],
         [7, 5, 9, 6, 2]]]])

In [50]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [57]:
# get the first 4 numbers of the inner most array
a4[:,:,:,:1]

array([[[[3],
         [5],
         [9],
         [3]],

        [[1],
         [7],
         [7],
         [3]],

        [[4],
         [9],
         [2],
         [9]]],


       [[[3],
         [7],
         [6],
         [7]],

        [[9],
         [6],
         [6],
         [9]],

        [[7],
         [8],
         [3],
         [7]]]])

## 4. Manipulating and comparing arrarys

## Arithmetic 

In [59]:
a1

array([1, 2, 3])

In [60]:
ones = np.ones(3)

In [61]:
a1 + ones

array([2., 3., 4.])

In [62]:
a1 - ones

array([0., 1., 2.])

In [63]:
a1 * ones

array([1., 2., 3.])

In [64]:
a2

array([[1. , 3. , 5.5],
       [4.5, 7. , 8. ]])

In [65]:
a1 * a2

array([[ 1. ,  6. , 16.5],
       [ 4.5, 14. , 24. ]])

In [66]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [74]:
a1 / ones

array([1., 2., 3.])

In [79]:
a2 ** 2

array([[ 0,  1],
       [ 4,  9],
       [16, 25]])

In [80]:
np.square(a2)

array([[ 0,  1],
       [ 4,  9],
       [16, 25]])

In [81]:
a1 % 2

array([1, 0, 1])