In [1]:
import numpy as np

## DataTypes and Attributes

In [2]:
# NumPy's main datatype is ndarray 
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [7]:
type(a1)

numpy.ndarray

In [14]:
a2 = np.array([
    [1,3,5.5],
    [4.5,7,8]
])
# 3-dimensional array, also referred to as a matrix
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])

In [15]:
a2

array([[1. , 3. , 5.5],
       [4.5, 7. , 8. ]])

In [16]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])