In [3]:
import numpy as np

## DataTypes and Attributes

In [12]:
# NumPy's main datatype is ndarray 
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [7]:
type(a1)

numpy.ndarray

In [9]:
a2 = np.array([[1.3,1,5.6],[6,1.7,9.6]])
a3 = np.array([[1,4,6],[7,4,5],[8,6,3]])

In [10]:
a2

array([[1.3, 1. , 5.6],
       [6. , 1.7, 9.6]])

In [11]:
a3

array([[1, 4, 6],
       [7, 4, 5],
       [8, 6, 3]])