In [3]:
import numpy as np

## DataTypes and Attributes

In [4]:
# NumPy's main datatype is ndarray 
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [5]:
type(a1)

numpy.ndarray

In [6]:
a2 = np.array([
    [1,3,5.5],
    [4.5,7,8]
])
# 3-dimensional array, also referred to as a matrix
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])

In [7]:
a2

array([[1. , 3. , 5.5],
       [4.5, 7. , 8. ]])

In [8]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [9]:
a1.shape

(3,)

In [10]:
a3.shape

(2, 3, 3)

In [11]:
a2.shape

(2, 3)