In [5]:
import numpy as np

## DataTypes and Attributes

In [6]:
# NumPy's main datatype is ndarray 
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [7]:
type(a1)

numpy.ndarray

In [8]:
a2 = np.array([
    [1,3,5.5],
    [4.5,7,8]
])
# 3-dimensional array, also referred to as a matrix
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])

In [9]:
a2

array([[1. , 3. , 5.5],
       [4.5, 7. , 8. ]])

In [10]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [11]:
a1.shape

(3,)

In [12]:
a3.shape

(2, 3, 3)

In [13]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [14]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [15]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [16]:
a1

array([1, 2, 3])

In [17]:
a2

array([[1. , 3. , 5.5],
       [4.5, 7. , 8. ]])

In [18]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [19]:
# create a dataframe from numpy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  3.0  5.5
1  4.5  7.0  8.0

## 2. Create Numpy arrays

In [20]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [21]:
sample_array.dtype

dtype('int64')

In [22]:
ones = np.ones((2, 3))

In [23]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [24]:
ones.dtype

dtype('float64')

In [25]:
type(ones)

numpy.ndarray

In [26]:
zeros = np.zeros((2, 3))

In [27]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
range_array = np.arange(0, 10,2)

In [29]:
range_array

array([0, 2, 4, 6, 8])

In [30]:
random_array = np.random.randint(0,10,size=(3,5))
random_array

array([[4, 9, 2, 7, 5],
       [1, 3, 8, 1, 0],
       [7, 0, 8, 0, 6]])

In [31]:
random_array.size

15

In [32]:
random_array.shape

(3, 5)

In [33]:
random_array_2 = np.random.random(size=(5, 3))
random_array_2

array([[0.30165829, 0.36656163, 0.81603158],
       [0.74069586, 0.90096282, 0.85458233],
       [0.45949187, 0.72020903, 0.22397833],
       [0.65659584, 0.00725991, 0.58901848],
       [0.86805729, 0.6581015 , 0.15328672]])

In [34]:
random_array_2.shape

(5, 3)

In [35]:
random_array_2.size

15

In [36]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.65954376, 0.03187006, 0.53579083],
       [0.82687154, 0.1917991 , 0.5427655 ],
       [0.30141209, 0.99620692, 0.36272989],
       [0.75577966, 0.07530862, 0.65905695],
       [0.29332906, 0.47374242, 0.15068201]])

In [37]:
#pseudo random arrays|
np.random.seed(seed=0)

random_array_4 = np.random.randint(10, size=(5, 3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [38]:
np.random.seed(7)
random_array_5 = np.random.random(size=((5, 3)))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [39]:
random_array_4.shape

(5, 3)

## 3. Viewing arrays and matrices

In [40]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
a1

array([1, 2, 3])

In [42]:
a2

array([[1. , 3. , 5.5],
       [4.5, 7. , 8. ]])

In [43]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [44]:
a1[0]

1

In [45]:
a2[0]

array([1. , 3. , 5.5])

In [46]:
a3.shape

(2, 3, 3)

In [47]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
a2

array([[1. , 3. , 5.5],
       [4.5, 7. , 8. ]])

In [49]:
a2[1]

array([4.5, 7. , 8. ])

In [50]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [51]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [52]:
a4 = np.random.randint(10, size=(2,3,4,5))

In [53]:
a4

array([[[[3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7],
         [3, 3, 8, 3, 0]],

        [[1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4],
         [3, 1, 3, 1, 3]],

        [[4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0],
         [9, 9, 3, 4, 5]]],


       [[[3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5],
         [7, 1, 5, 4, 4]],

        [[9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6],
         [9, 8, 6, 5, 9]],

        [[7, 5, 4, 9, 6],
         [8, 1, 5, 5, 8],
         [3, 7, 7, 9, 4],
         [7, 5, 9, 6, 2]]]])

In [54]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [55]:
# get the first 4 numbers of the inner most array
a4[:,:,:,:1]

array([[[[3],
         [5],
         [9],
         [3]],

        [[1],
         [7],
         [7],
         [3]],

        [[4],
         [9],
         [2],
         [9]]],


       [[[3],
         [7],
         [6],
         [7]],

        [[9],
         [6],
         [6],
         [9]],

        [[7],
         [8],
         [3],
         [7]]]])

## 4. Manipulating and comparing arrarys

## Arithmetic 

In [56]:
a1

array([1, 2, 3])

In [57]:
ones = np.ones(3)

In [58]:
a1 + ones

array([2., 3., 4.])

In [59]:
a1 - ones

array([0., 1., 2.])

In [60]:
a1 * ones

array([1., 2., 3.])

In [61]:
a2

array([[1. , 3. , 5.5],
       [4.5, 7. , 8. ]])

In [62]:
a1 * a2

array([[ 1. ,  6. , 16.5],
       [ 4.5, 14. , 24. ]])

In [63]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [64]:
a1 / ones

array([1., 2., 3.])

In [65]:
a2 ** 2

array([[ 1.  ,  9.  , 30.25],
       [20.25, 49.  , 64.  ]])

In [66]:
np.square(a2)

array([[ 1.  ,  9.  , 30.25],
       [20.25, 49.  , 64.  ]])

In [67]:
a1 % 2

array([1, 0, 1])

### Aggregation

Aggregarion = performing tha same operation on a number of things

In [68]:
listy_list = [1,2,3]
type(listy_list)

list

In [69]:
sum(listy_list)

6

In [70]:
a1

array([1, 2, 3])

In [71]:
type(a1)

numpy.ndarray

In [72]:
sum(a1)

6

In [73]:
np.sum(a1)

6

use Pythons data methods on python datatypes (`sum()`)
use numpy on numpy methods

In [74]:
# create massive array
massiva_array = np.random.random(100000)
massiva_array.size

100000

In [75]:
massiva_array[:10]

array([0.82845319, 0.94180927, 0.12814785, 0.23043067, 0.6591584 ,
       0.13247399, 0.22407864, 0.57486259, 0.16952372, 0.78223015])

In [76]:
%timeit sum(massiva_array)
%timeit np.sum(massiva_array)

13.5 ms ± 814 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
26.2 µs ± 559 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
